config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'documents#index'
  
  resources :categories
  resources :documents
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_ancestry

  ### RELATIONS ###
  has_many :documents
end

app/models/document.rb
class Document < ActiveRecord::Base
  mount_uploader :pdf, PdfUploader

  ### CALLBACKS ###
  before_create :set_defaults

  ### VALIDATIONS ###
  validates :pdf, presence: true
  validates :category, presence: true

  ### RELATIONS ###
  belongs_to :category

  def set_defaults
    url = self.pdf.url
    uri = URI.parse(url)
    self.description = File.basename(uri.path, ".*" )
    self.title = File.basename(uri.path, ".*" )
  end

  def self.search(query)
    where('description like ?', "%#{query}%")
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable :recoverable,
  devise :database_authenticatable, :rememberable, :trackable, :validatable, :recoverable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :check_admin, only: [:new, :create, :update, :destroy, :edit]
  before_action :set_category, only: [:edit, :update, :destroy, :show]

  def new
    @category = Category.new
    @title = params[:title]
  end

  def edit
  end

  def show
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to @category, notice: 'Categorie aangemaakt!'
    else
      render :new
    end
  end

  def update
    if @category.update(category_params)
      redirect_to documents_path, notice: 'Categorie aangepast!'
    else
      render :edit
    end
  end

  private
    def category_params
      params.require(:category).permit(:title, :parent_id)
    end

    def set_category
      @category = Category.find(params[:id])
    end

    def check_admin
      if !current_user.admin
        redirect_to root_path, alert: 'U bent niet gemachtigd!'
      end
    end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :check_admin, only: [:new, :create, :update, :destroy, :edit]

  def index
    if params[:search]
      @documents = Document.search(params[:search])
      render json: @documents
    else
      @documents = Document.all
    end
  end

  def show
  end

  def new
    @document = Document.new
  end

  def create
    @document = Document.new(document_params)
    if @document.save
      redirect_to @document.category, notice: 'Bestand geupload!'
    else
      render :new, alert: 'Uploaden mislukt!'
    end
  end

  def edit
  end

  def update
    if @document.update(document_params)
      redirect_to documents_path, notice: 'Bestand aangepast!'
    else
      render :edit, alert: 'Aanpassen mislukt!'
    end
  end

  def destroy
    @document.destroy
    redirect_to documents_path, notice: 'Bestand verwijderd!'
  end

  private
    def document_params
      params.require(:document).permit(:title, :description, :pdf, :category_id)
    end

    def set_document
      @document = Document.find(params[:id])
    end

    def check_admin
      if !current_user.admin
        redirect_to root_path, alert: 'U bent niet gemachtigd!'
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/_form.html.erb
<%= form_for @category do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %></h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <p><%= f.text_field :title, placeholder: 'Voer een titel in...' %></p>
  <p><%= f.collection_select :parent_id, Category.order(:title), :id, :title, include_blank: true, value: 6 %></p>
  <p><%= f.submit %></p>
<% end %>

app/views/categories/_submenu_categories.html.erb
<% categories.each do |category, children| %>
  <div class='panel panel-default'>
    <div class='panel-body'>
      <%= link_to_unless_current category.title, category %><span class="badge"><%= category.children.count if category.children.count > 0 %></span>
    </div>
    <%= render 'submenu_categories', categories: children if children.present? %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Categorie aanpassen</h1>

<%= render 'form' %>

app/views/categories/new.html.erb
<h1>Category toevoegen</h1>

<%= render 'form' %>

app/views/categories/show.html.erb
<h1>Documenten van <%= @category.title %></h1>
<%= link_to 'Categorie toevoegen in de categorie "' + @category.title + '"', new_category_path(category: @category), class: 'glyphicon glyphicon-plus' %> 

<table class='table table-striped table-hover table-bordered'>
  <tr>
    <th>PDF</th>
    <th>Beschrijving</th>
    <th>Toegevoegd op</th>
  </tr>

  <% @category.documents.order("title ASC").each do |document| %>
    </tr>
      <td><%= link_to document.title, document.pdf.url, target: '_blank' %></td>
      <td><%= document.description %></td>
      <td><%= document.created_at.strftime('%d-%m-%Y %H:%M') %></td>
      <% if current_user.admin %>
        <td>
          <%= link_to '', edit_document_path(document), class: 'glyphicon glyphicon-pencil' %>
          <%= link_to '', document, method: :delete, data: { confirm: 'Weet je zeker dat je dit document wilt verwijderen?' }, class: 'glyphicon glyphicon-remove' %>
        </td>
      <% end %>
    </tr>
  <% end %>
</table>

app/views/documents/_form.html.erb
<%= form_for @document do |f| %>
  <% if @document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@document.errors.count, "error") %></h2>

      <ul>
      <% @document.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <p><%= f.file_field :pdf %></p>
  <p>
    Categorie: <%= f.collection_select(:category_id, Category.all, :id, :title) %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/documents/edit.html.erb
<h1>Document aanpassen</h1>

<%= render 'form' %>

app/views/documents/index.html.erb
<h1>Welkom bij de documententool</h1>
<h3>Kies hierboven een categorie</h3>
<h3>Zoek op documenten:</h3>

<%= form_tag(root_path, method: 'get', remote: true, class: 'jsFindDocument') do %>
  <%= text_field_tag :search, params[:search], placeholder: 'Zoek op documentnaam', class: 'jsSearchForm' %>
<% end %>

<ul class='jsFoundDocuments'>

</ul>

<h4>Versie geschiedenis:</h4>
<p>Versie 1.4</p>
<p>
  <ul>
    <li>Er kunnen nu categorieen in categorieen worden toegevoegd.</li>
    <li>Er kan nu gezien worden in welke categorie en subcategorie de gebruiker zich bevind.</li>
    <li>Documenten en categorieen moeten nu in een categorie worden aangemaakt ipv gekozen worden uit een lijst.</li>
  </ul>
</p>

<p>Versie 1.3</2p>
<p>
  <ul>
    <li>De naam van een pdf wordt nu als standaard naam en beschrijving gezet.</li>
  </ul>
</p>

<p>Versie 1.3</2p>
<p>
  <ul>
    <li>Er kunnen categorieen toegewezen worden aan documenten.</li>
  </ul>
</p>

<p>Versie 1.1</p>
<p>
  <ul>
    <li>Documenten kunnen geupload worden.</li>
  </ul>
</p>

app/views/documents/new.html.erb
<h1>Document toevoegen</h1>

<%= render 'form' %>

app/views/documents/show.html.erb
<h1><%= @document.title %></h1>
<p><%= @document.description %></p>
<%= link_to 'open pdf', @document.pdf.url, target: '_blank' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Documenten Tool</title>
  <meta name='viewport' content='width=device-width, initial-scale=1, user-scalable=no'/>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
  <body>   
    <div class='row'>
      <div class='navbar navbar-inverse'>
        <p class='navbar-text'>Documententool 1.4</p>
        <%= link_to 'Home', documents_path, class: 'navbar-brand' %>
        <% if user_signed_in? && current_user.admin %>
          <%= link_to 'Document toevoegen', new_document_path, class: 'navbar-brand' %>
          <%= link_to 'Categorie toevoegen', new_category_path, class: 'navbar-brand' %>
        <% end %>

        <div class='pull-right'>
          <div class='navbar-brand'>Ingelogd als <%= current_user.email if user_signed_in? %></div>
          <%= link_to 'Uitloggen', destroy_user_session_path, class: 'navbar-brand', method: "delete" %>
        </div>
      </div>
        <% if notice %>
          <span><%= notice %></span>
        <% elsif alert %>
          <span><%= alert %></span>
        <% end %>
      <div class='wrapper'>
        <div class='col-md-3'>
          <div class='submenu'>
            <% if @category && params[:action] == 'show' %>
              <%= render 'categories/submenu_categories', categories: @category.root.descendants.arrange %>
            <% end %>
          </div>
        </div>

        <div class='col-md-9'>
          <div class='panel panel-default'>
            <ul class="nav nav-pills">
              <% Category.roots.each do |category| %>
                <li role="presentation" <% if @category && @category.root == category %>class='active'<% end %>>
                  <%= link_to category.title, category %>
                </li>
              <% end %>
            </ul>
            <div class='panel-body'>
              <% if @category && @category.ancestors.any? %>
                <div id='breadcrumbs'>
                  <ol class="breadcrumb">
                    <% @category.ancestors.each do |category| %>
                      <li><%= link_to category.title, category %></li>
                    <% end %>
                  </ol>
                </div>
              <% end %>
              <%= yield %>
            </div>
          </div>

        </div>
      </div>
    </div>
  </body>
</html>